services:
  influxdb:
    image: influxdb
    ports:
      - 8086:8086
    volumes:
      - influxdb2:/var/lib/influxdb2
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana

volumes:
  influxdb2:
  grafana:
